// ─── Facilities & Arenas ──────────────────────────────────────────────────────
// Shared between create form and admin dashboard

export const FACILITIES = [
  { id: 1,   name: 'Urbansports Shaktimills',       city: 'Mumbai' },
  { id: 5,   name: 'Score Indoor Pickleball',        city: 'Mumbai' },
  { id: 6,   name: 'Score Marwah - Sakinaka',        city: 'Mumbai' },
  { id: 7,   name: 'Torba Pali Hill',                city: 'Mumbai' },
  { id: 8,   name: 'Padel Project - Powai',          city: 'Mumbai' },
  { id: 9,   name: 'The CourtRoom',                  city: 'Mumbai' },
  { id: 10,  name: 'Shuttle Whizz Badminton',        city: 'Mumbai' },
  { id: 12,  name: 'LvL One Pickleball',             city: 'Mumbai' },
  { id: 13,  name: 'ACE PADEL',                      city: 'Mumbai' },
  { id: 43,  name: 'Serve Society',                  city: 'Mumbai' },
  { id: 44,  name: 'KickForAll',                     city: 'Mumbai' },
  { id: 76,  name: 'Hurdles Ghatkopar',              city: 'Mumbai' },
  { id: 109, name: 'Common grounds Thane',           city: 'Thane' },
  { id: 142, name: 'Epic Play',                      city: 'Mumbai' },
  { id: 175, name: 'Hurdles Chembur',                city: 'Mumbai' },
  { id: 208, name: 'Arena X - Pickleball Court',     city: 'Pune' },
  { id: 209, name: 'The Pickle Point',               city: 'Pune' },
  { id: 210, name: 'GoRally Pickleball Sarjapur',    city: 'Bengaluru' },
  { id: 211, name: 'GoRally Pickleball Jayamahal',   city: 'Bengaluru' },
  { id: 241, name: 'Pickleball Arena',               city: 'Mumbai' },
  { id: 274, name: 'Iron Pickleball',                city: 'Mumbai' },
  { id: 307, name: 'Courtside',                      city: 'Mumbai' },
  { id: 340, name: 'Padelverse Ranibaug',            city: 'Mumbai' },
  { id: 373, name: '11 Point Club',                  city: 'Bengaluru' },
];

// Arena names per facility (keyed by facility ID)
export const FACILITY_ARENAS = {
  1:   ['Court 1'],
  5:   ['Court 1', 'Court 2'],
  6:   ['Football', 'Cricket'],
  7:   ['Court 1 Mango', 'Court 2 Lime', 'Court 3 Mixed'],
  8:   ['Court 1'],
  9:   ['Padel', 'Pickleball', 'Pickleball 2'],
  10:  ['Court 1'],
  12:  ['Court 1', 'Court 2'],
  13:  ['Court 1'],
  43:  ['Padel Court 1', 'Padel Court 2', 'Padel Court 3', 'Pickleball'],
  44:  ['Court 1'],
  76:  ['Pickleball Court 1', 'Pickleball Court 2', 'Padel', 'Badminton Court 1', 'Badminton Court 2', 'Badminton Court 3'],
  109: ['Padel Court', 'Pickleball Court 1', 'Pickle Cafe Side'],
  142: ['Padel', 'Pickleball 1', 'Pickleball 2', 'Pickleball 3'],
  175: ['Pickleball 1', 'Pickleball 2', 'Badminton 1', 'Badminton Court 2', 'Badminton Court 3'],
  208: ['Play Court 1', 'Push Court 2', 'Perform Court 3', 'Repeat Court 4'],
  209: ['Pickleball Court 1', 'Pickleball Court 2', 'Pickleball Court 3', 'Pickleball Court 4'],
  210: ['Pickelball Court 1', 'Pickelball Court 2', 'Pickelball Court 3', 'Pickelball Court 4'],
  211: ['Pickleball Court 1', 'Pickleball Court 2'],
  241: ['Pickleball Court 1'],
  274: ['Pickleball'],
  307: ['Pickleball', 'Padel Court 1', 'Padel Court 2', 'Padel Court 3'],
  340: ['Padel Court 1', 'Padel Court 2', 'Padel Court 3', 'Padel Court 4', 'Pickleball Court 1', 'Pickleball Court 2'],
  373: ['Pickleball Court 1', 'Pickleball Court 2', 'Pickleball Court 3', 'Pickleball Court 4', 'Pickleball Court 5'],
};
